[project]
name = "agntcy-dir"
version = "1.5.0"
description = "Directory SDK"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "agntcy-dir-grpc-python==1.81.1.1.20260617162622+804385aa416f",            # v1.5.0
    "agntcy-dir-protocolbuffers-python==35.1.0.1.20260617162622+804385aa416f", # v1.5.0
    "authlib>=1.6.9",
    "httpx>=0.28.1",
    "grpcio>=1.78.0",
    "protobuf>=7.35.1",
    "pyasn1>=0.6.3",
    "spiffe>=0.2.6",
    "spiffe-tls>=0.3.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.0",
    "pytest-cov>=6.0.0",
    "uuid>=1.30",
    "mypy==2.3.0",
    "ruff==0.16.2",
    "pydantic>=2.13.4",
]

[[tool.uv.index]]
name = "buf"
url = "https://buf.build/gen/python"

[tool.uv.sources]
agntcy-dir-grpc-python = { index = "buf" }
agntcy-dir-protocolbuffers-python = { index = "buf" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = ["/dir-sdk-python/agntcy/dir_sdk/tests"]

[tool.hatch.build.targets.wheel]
packages = ["dir-sdk-python/agntcy"]

[tool.pytest.ini_options]
pythonpath = ["dir-sdk-python"]
addopts = ["--import-mode=importlib"]

[tool.ruff.lint]
extend-select = ["ANN", "ARG", "ASYNC", "B", "I", "N", "SIM"]

[tool.ruff.lint.per-file-ignores]
"dir-sdk-python/agntcy/dir_sdk/models/*.py" = ["F403"]

[tool.mypy]
python_version = "3.11"
mypy_path = "dir-sdk-python"
explicit_package_bases = true
exclude_gitignore = true
warn_return_any = false
warn_unused_configs = true
warn_unused_ignores = true
plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = ["grpc.*", "google.*", "authlib.*", "spiffe.*"]
ignore_missing_imports = true
